### ISSUE TITLE
Sette opp dummy amplitude test konto

### ISSUE THREAD

**Issue by ivaruf** [oslokommune/amplitude-proxy#1]

**Comment by endremm** [comment]
Da har jeg satt opp testkonto i Amplitude med organisasjon `Oslo kommune (origo-test)` og org-url `oslo-origo`.

Du har blitt invitert til kontoen med egen bruker, @ivaruf, og jeg håper du har fått admin-rettigheter som meg.

~~https://analytics.amplitude.com/oslo-origo/home~~

https://analytics.eu.amplitude.com/oslo-origo/home

**Comment by endremm** [comment]
Verifisert at data har kommet inn.
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/1925255/232588638-52e4eba7-3c7d-425e-bf2c-9a7f291bb11e.png">
