### ISSUE TITLE
Kjøre amplitude-proxy i AWS apprunner

### ISSUE THREAD

**Issue by ivaruf** [oslokommune/amplitude-proxy#3]
Finn ut hva som trengs av env variables, legg eventuelt ting i github secrets for dette repo, slik at vi kan bygge docker containere i github actions.

**Comment by endremm** [comment]
IAC-kode for ECR-repository:
https://github.com/oslokommune/origo-aws-iac/pull/67

IAC-kode for å kjøre som AppRunner:
https://github.com/oslokommune/origo-aws-iac/pull/68

PR med kode-tweaks for å kjøre i Origo:
https://github.com/navikt/amplitude-proxy/pull/405

(sistnevnte PR ble dessverre pushet til Nav 😢 uten at jeg merket det)

**Comment by endremm** [comment]
Mener at vi er i mål med denne nå. Akkurat nå ser det ikke ut til at Amplitude blir valgt likevel.
